# Teste do módulo sequência visível usando a biblioteca contendo o arcabouço

[Diretorios]

Nome        =  TesteVisivel
PathDefault =  ..\Fontes
err         =  ..\Produto
obj         =  ..\Objetos
c           =  ..\Fontes
h           =  ..\Fontes
def         =  ..\Tabelas

[Modulos]
Carta
Lista
Visivel
TestVis

[BuildInicio]
/OUT:..\produto\TRAB4-7.exe
/INCREMENTAL:NO
/MACHINE:IX86

[BuildFim]
ArcaboucoTeste.lib

[Fim]
