# Teste do módulo extras usando a biblioteca contendo o arcabouço

[Diretorios]

Nome        =  TesteExtras
PathDefault =  ..\Fontes
err         =  ..\Produto
obj         =  ..\Objetos
c           =  ..\Fontes
h           =  ..\Fontes
def         =  ..\Tabelas

[Modulos]
Carta
Lista
Extras
TestExt

[BuildInicio]
/OUT:..\produto\TRAB4-5.exe
/INCREMENTAL:NO
/MACHINE:IX86

[BuildFim]
ArcaboucoTeste.lib

[Fim]
