
# Teste do módulo carta usando a biblioteca contendo o arcabouço

[Diretorios]

Nome        =  TesteCarta
PathDefault =  ..\Fontes
err         =  ..\Produto
obj         =  ..\Objetos
c           =  ..\Fontes
h           =  ..\Fontes

[Modulos]
CARTA     
TESTCAR   

[BuildInicio]
/OUT:..\Produto\TRAB4-1.exe
/INCREMENTAL:NO
/MACHINE:IX86

[BuildFim]
ArcaboucoTeste.lib

[Fim]
