# Teste do módulo ordenada usando a biblioteca contendo o arcabouço

[Diretorios]

Nome        =  TesteOrdenada
PathDefault =  ..\Fontes
err         =  ..\Produto
obj         =  ..\Objetos
c           =  ..\Fontes
h           =  ..\Fontes
def         =  ..\Tabelas

[Modulos]
Carta
Lista
Ordenada
TestOrd

[BuildInicio]
/OUT:..\produto\TRAB4-6.exe
/INCREMENTAL:NO
/MACHINE:IX86

[BuildFim]
ArcaboucoTeste.lib

[Fim]
